# Generated by Django 4.0.5 on 2022-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_date_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter your post name', max_length=200),
        ),
    ]
